name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:          
          context: "{{defaultContext}}:server"
          push: true
          tags: yuniyakim/to-do-list_web-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Copy repository content via scp 
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets. HOST }}
          USERNAME: ${{ secrets. USERNAME }} 
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets. PORT }}
        with:
          source: "."
          target: "/opt/to-do-list_web-server"
          
      - name: Executing remote command 
        uses: appleboy/ssh-action@master 
        with:
          HOST: ${{ secrets. HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          SCRIPT: >
            cd /opt/to-do-list_web-server &&
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            make compose_up
              
